/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.scclexer.node;

import org.sableccsupport.scclexer.analysis.*;

@SuppressWarnings("nls")
public final class TIgnored extends Token
{
    public TIgnored()
    {
        super.setText("Ignored");
    }

    public TIgnored(int line, int pos)
    {
        super.setText("Ignored");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIgnored(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIgnored(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIgnored text.");
    }
}
