/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import java.util.*;
import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class AAlts extends PAlts
{
    private PAlt _alt_;
    private final LinkedList<PAltsTail> _alts_ = new LinkedList<PAltsTail>();

    public AAlts()
    {
        // Constructor
    }

    public AAlts(
        @SuppressWarnings("hiding") PAlt _alt_,
        @SuppressWarnings("hiding") List<PAltsTail> _alts_)
    {
        // Constructor
        setAlt(_alt_);

        setAlts(_alts_);

    }

    @Override
    public Object clone()
    {
        return new AAlts(
            cloneNode(this._alt_),
            cloneList(this._alts_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlts(this);
    }

    public PAlt getAlt()
    {
        return this._alt_;
    }

    public void setAlt(PAlt node)
    {
        if(this._alt_ != null)
        {
            this._alt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alt_ = node;
    }

    public LinkedList<PAltsTail> getAlts()
    {
        return this._alts_;
    }

    public void setAlts(List<PAltsTail> list)
    {
        this._alts_.clear();
        this._alts_.addAll(list);
        for(PAltsTail e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alt_)
            + toString(this._alts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alt_ == child)
        {
            this._alt_ = null;
            return;
        }

        if(this._alts_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alt_ == oldChild)
        {
            setAlt((PAlt) newChild);
            return;
        }

        for(ListIterator<PAltsTail> i = this._alts_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAltsTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
