/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class AAltsTail extends PAltsTail
{
    private TBar _bar_;
    private PAlt _alt_;

    public AAltsTail()
    {
        // Constructor
    }

    public AAltsTail(
        @SuppressWarnings("hiding") TBar _bar_,
        @SuppressWarnings("hiding") PAlt _alt_)
    {
        // Constructor
        setBar(_bar_);

        setAlt(_alt_);

    }

    @Override
    public Object clone()
    {
        return new AAltsTail(
            cloneNode(this._bar_),
            cloneNode(this._alt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAltsTail(this);
    }

    public TBar getBar()
    {
        return this._bar_;
    }

    public void setBar(TBar node)
    {
        if(this._bar_ != null)
        {
            this._bar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bar_ = node;
    }

    public PAlt getAlt()
    {
        return this._alt_;
    }

    public void setAlt(PAlt node)
    {
        if(this._alt_ != null)
        {
            this._alt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bar_)
            + toString(this._alt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bar_ == child)
        {
            this._bar_ = null;
            return;
        }

        if(this._alt_ == child)
        {
            this._alt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bar_ == oldChild)
        {
            setBar((TBar) newChild);
            return;
        }

        if(this._alt_ == oldChild)
        {
            setAlt((PAlt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
