/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import java.util.*;
import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class AIdList extends PIdList
{
    private TId _id_;
    private final LinkedList<PIdListTail> _ids_ = new LinkedList<PIdListTail>();

    public AIdList()
    {
        // Constructor
    }

    public AIdList(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<PIdListTail> _ids_)
    {
        // Constructor
        setId(_id_);

        setIds(_ids_);

    }

    @Override
    public Object clone()
    {
        return new AIdList(
            cloneNode(this._id_),
            cloneList(this._ids_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdList(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PIdListTail> getIds()
    {
        return this._ids_;
    }

    public void setIds(List<PIdListTail> list)
    {
        this._ids_.clear();
        this._ids_.addAll(list);
        for(PIdListTail e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._ids_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._ids_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PIdListTail> i = this._ids_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIdListTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
