/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class AListTermTail extends PListTermTail
{
    private TComma _comma_;
    private PListTerm _listTerm_;

    public AListTermTail()
    {
        // Constructor
    }

    public AListTermTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PListTerm _listTerm_)
    {
        // Constructor
        setComma(_comma_);

        setListTerm(_listTerm_);

    }

    @Override
    public Object clone()
    {
        return new AListTermTail(
            cloneNode(this._comma_),
            cloneNode(this._listTerm_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListTermTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PListTerm getListTerm()
    {
        return this._listTerm_;
    }

    public void setListTerm(PListTerm node)
    {
        if(this._listTerm_ != null)
        {
            this._listTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listTerm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._listTerm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._listTerm_ == child)
        {
            this._listTerm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._listTerm_ == oldChild)
        {
            setListTerm((PListTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
