/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class ALookAhead extends PLookAhead
{
    private TSlash _slash_;
    private PRegExp _regExp_;

    public ALookAhead()
    {
        // Constructor
    }

    public ALookAhead(
        @SuppressWarnings("hiding") TSlash _slash_,
        @SuppressWarnings("hiding") PRegExp _regExp_)
    {
        // Constructor
        setSlash(_slash_);

        setRegExp(_regExp_);

    }

    @Override
    public Object clone()
    {
        return new ALookAhead(
            cloneNode(this._slash_),
            cloneNode(this._regExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALookAhead(this);
    }

    public TSlash getSlash()
    {
        return this._slash_;
    }

    public void setSlash(TSlash node)
    {
        if(this._slash_ != null)
        {
            this._slash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._slash_ = node;
    }

    public PRegExp getRegExp()
    {
        return this._regExp_;
    }

    public void setRegExp(PRegExp node)
    {
        if(this._regExp_ != null)
        {
            this._regExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._regExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._slash_)
            + toString(this._regExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._slash_ == child)
        {
            this._slash_ = null;
            return;
        }

        if(this._regExp_ == child)
        {
            this._regExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._slash_ == oldChild)
        {
            setSlash((TSlash) newChild);
            return;
        }

        if(this._regExp_ == oldChild)
        {
            setRegExp((PRegExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
