/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class APkgNameTail extends PPkgNameTail
{
    private TDot _dot_;
    private TPkgId _pkgId_;

    public APkgNameTail()
    {
        // Constructor
    }

    public APkgNameTail(
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TPkgId _pkgId_)
    {
        // Constructor
        setDot(_dot_);

        setPkgId(_pkgId_);

    }

    @Override
    public Object clone()
    {
        return new APkgNameTail(
            cloneNode(this._dot_),
            cloneNode(this._pkgId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPkgNameTail(this);
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TPkgId getPkgId()
    {
        return this._pkgId_;
    }

    public void setPkgId(TPkgId node)
    {
        if(this._pkgId_ != null)
        {
            this._pkgId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pkgId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dot_)
            + toString(this._pkgId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._pkgId_ == child)
        {
            this._pkgId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._pkgId_ == oldChild)
        {
            setPkgId((TPkgId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
