/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import java.util.*;
import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class ARegExp extends PRegExp
{
    private PConcat _concat_;
    private final LinkedList<PRegExpTail> _concats_ = new LinkedList<PRegExpTail>();

    public ARegExp()
    {
        // Constructor
    }

    public ARegExp(
        @SuppressWarnings("hiding") PConcat _concat_,
        @SuppressWarnings("hiding") List<PRegExpTail> _concats_)
    {
        // Constructor
        setConcat(_concat_);

        setConcats(_concats_);

    }

    @Override
    public Object clone()
    {
        return new ARegExp(
            cloneNode(this._concat_),
            cloneList(this._concats_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARegExp(this);
    }

    public PConcat getConcat()
    {
        return this._concat_;
    }

    public void setConcat(PConcat node)
    {
        if(this._concat_ != null)
        {
            this._concat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concat_ = node;
    }

    public LinkedList<PRegExpTail> getConcats()
    {
        return this._concats_;
    }

    public void setConcats(List<PRegExpTail> list)
    {
        this._concats_.clear();
        this._concats_.addAll(list);
        for(PRegExpTail e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._concat_)
            + toString(this._concats_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._concat_ == child)
        {
            this._concat_ = null;
            return;
        }

        if(this._concats_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._concat_ == oldChild)
        {
            setConcat((PConcat) newChild);
            return;
        }

        for(ListIterator<PRegExpTail> i = this._concats_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRegExpTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
