/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sableccsupport.sccparser.node;

import java.util.*;
import org.sableccsupport.sccparser.analysis.*;

@SuppressWarnings("nls")
public final class ATokens extends PTokens
{
    private TTokens _tokens_;
    private final LinkedList<PTokenDef> _tokenDefs_ = new LinkedList<PTokenDef>();

    public ATokens()
    {
        // Constructor
    }

    public ATokens(
        @SuppressWarnings("hiding") TTokens _tokens_,
        @SuppressWarnings("hiding") List<PTokenDef> _tokenDefs_)
    {
        // Constructor
        setTokens(_tokens_);

        setTokenDefs(_tokenDefs_);

    }

    @Override
    public Object clone()
    {
        return new ATokens(
            cloneNode(this._tokens_),
            cloneList(this._tokenDefs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATokens(this);
    }

    public TTokens getTokens()
    {
        return this._tokens_;
    }

    public void setTokens(TTokens node)
    {
        if(this._tokens_ != null)
        {
            this._tokens_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tokens_ = node;
    }

    public LinkedList<PTokenDef> getTokenDefs()
    {
        return this._tokenDefs_;
    }

    public void setTokenDefs(List<PTokenDef> list)
    {
        this._tokenDefs_.clear();
        this._tokenDefs_.addAll(list);
        for(PTokenDef e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tokens_)
            + toString(this._tokenDefs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tokens_ == child)
        {
            this._tokens_ = null;
            return;
        }

        if(this._tokenDefs_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tokens_ == oldChild)
        {
            setTokens((TTokens) newChild);
            return;
        }

        for(ListIterator<PTokenDef> i = this._tokenDefs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTokenDef) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
